version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: diet_fitness_db
    environment:
      POSTGRES_USER: andyrosty
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: diet_fitness_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data: