version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: diet_fitness_app
    environment:
      DATABASE_URL: postgresql://andyrosty:pass1234@postgres:5432/diet_fitness_db
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    restart: unless-stopped
    volumes:
      - ./:/app

  postgres:
    image: postgres:15
    container_name: diet_fitness_db
    environment:
      POSTGRES_USER: andyrosty
      POSTGRES_PASSWORD: pass1234
      POSTGRES_DB: diet_fitness_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
